apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "python-app.fullname" . }}
spec:
  schedule: "* * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-container
            image: "{{ .Values.cronJob.image.repository }}:{{ .Values.cronJob.image.tag }}"
            imagePullPolicy: {{ .Values.cronJob.image.pullPolicy | default "IfNotPresent" }}
          restartPolicy: OnFailure