name: build_and_deploy

on:
  push:
    branches:
      - main
      
permissions:
   id-token: write
   contents: read
   actions: read      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV  

      - name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}    
      -
        name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pythonapp:latest,${{ secrets.DOCKERHUB_USERNAME }}/pythonapp:${{ env.COMMIT_SHORT_SHA }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/setup-kubectl@v2.0    

      - uses: Azure/k8s-set-context@v2
        with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - uses: azure/k8s-bake@v2
        with:
          renderEngine: 'helm'
          helmChart: './helm-pyhton-app/'
          # overrideFiles: './helm-pyhton-app/values.yaml'
          # overrides: |
          #   replicas:2
          #   helm-version: 'latest'
          id: bake  

      - name: Deploy Helm chart
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          # images: |
          #   demo.azurecr.io/k8sdemo:${{ github.sha }}
          # imagepullsecrets: |
          #   demo-k8s-secret